// Generated by the Phase 3 seed script. Maps seeded backend UUIDs back to the
// legacy mock identifiers so the agenda UI keeps working with the same ids.
export const SEED_DENTIST_ID_BY_UUID: Record<string, string> = {
  "b925d862-1b40-45a4-8f82-126e8443fb60": "1",
  "af95e6f5-9448-4067-b23e-31b3d062913a": "2",
  "8f855138-6c87-48ed-bb3c-453087bf9784": "3",
  "ab4212ff-23a6-484e-acb6-703cd345d54d": "4",
  "181975e9-8ef0-46da-ae84-5ad21eae930d": "5",
  "1e3fa40c-3103-476c-935c-5aa4fa8384e4": "6",
  "ac0a21f0-d1a5-4677-8eed-c4be574c1af9": "7"
};

export const SEED_CLINIC_ID_BY_UUID: Record<string, string> = {
  "c9c4b85b-3a8b-47c3-b423-b1c5afd437fd": "1",
  "22d1b353-e031-483b-af83-23cc7896db53": "2",
  "3f3691b5-c58c-4bd9-9b54-c994a3a42292": "3"
};

export const SEED_DENTIST_UUID_BY_ID: Record<string, string> = {
  "1": "b925d862-1b40-45a4-8f82-126e8443fb60",
  "2": "af95e6f5-9448-4067-b23e-31b3d062913a",
  "3": "8f855138-6c87-48ed-bb3c-453087bf9784",
  "4": "ab4212ff-23a6-484e-acb6-703cd345d54d",
  "5": "181975e9-8ef0-46da-ae84-5ad21eae930d",
  "6": "1e3fa40c-3103-476c-935c-5aa4fa8384e4",
  "7": "ac0a21f0-d1a5-4677-8eed-c4be574c1af9"
};

export const SEED_CLINIC_UUID_BY_ID: Record<string, string> = {
  "1": "c9c4b85b-3a8b-47c3-b423-b1c5afd437fd",
  "2": "22d1b353-e031-483b-af83-23cc7896db53",
  "3": "3f3691b5-c58c-4bd9-9b54-c994a3a42292"
};
